/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArtesSlugRouteImport } from './routes/artes.$slug'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ArtesSlugRoute = ArtesSlugRouteImport.update({
  id: '/artes/$slug',
  path: '/artes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/artes/$slug': typeof ArtesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/planos'
    | '/reset-password'
    | '/suporte'
    | '/admin'
    | '/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/planos'
    | '/reset-password'
    | '/suporte'
    | '/admin'
    | '/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/planos'
    | '/reset-password'
    | '/suporte'
    | '/_authenticated/admin'
    | '/_authenticated/minha-conta'
    | '/artes/$slug'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuporteRoute: typeof SuporteRoute
  ArtesSlugRoute: typeof ArtesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/artes/$slug': {
      id: '/artes/$slug'
      path: '/artes/$slug'
      fullPath: '/artes/$slug'
      preLoaderRoute: typeof ArtesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuporteRoute: SuporteRoute,
  ArtesSlugRoute: ArtesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
